name: sreerajp_project_board
description: A project management app with rich text notes and checklists

environment:
  sdk: '^3.8.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  sqflite: ^2.3.0
  path: ^1.8.3
  path_provider: ^2.1.1
  intl: 0.20.2
  flutter_quill: ^11.4.1
  provider: ^6.1.1
  uuid: ^4.2.1
  flutter_staggered_animations: ^1.1.1  # Add for animations
  drag_and_drop_lists: ^0.4.1  # Add for drag and drop
  fl_chart: ^0.68.0
  permission_handler: ^11.0.1
  share_plus: ^7.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
